server:
  port: 9090
  servlet:
    session.timeout: 60000
    context-path: /yc74ibike
  undertow:
    io-threads: 16
    worker-threads: 256
    buffer-size: 1024
    buffers-per-regions: 1024
    direct-buffers: true
logging:
  level.root: error
  level.org.springframework: error
  level.com.yc: info
swagger:
  enabled: true
